In [1]:
#%matplotlib inline
%time from hikyuu.interactive import *

2025-08-11 23:24:29,506 [INFO] runing in interactive session [<module>] (D:\workspace\hikyuu\hikyuu\__init__.py:109) [hikyuu::hku_info]
2025-08-11 23:24:29,507 [INFO] running in jupyter [<module>] (D:\workspace\hikyuu\hikyuu\__init__.py:116) [hikyuu::hku_info]

current plugin path: D:\workspace\hikyuu\hikyuu\plugin
2025-08-11 23:24:29.570 [HKU-I] - Using MYSQL BaseInfoDriver (BaseInfoDriver.cpp:57)
2025-08-11 23:24:29.599 [HKU-I] - 加载市场信息…… (StockManager.cpp:572)
2025-08-11 23:24:29.606 [HKU-I] - 加载证券类型信息…… (StockManager.cpp:590)
2025-08-11 23:24:29.612 [HKU-I] - 加载证券信息…… (StockManager.cpp:476)
2025-08-11 23:24:29.744 [HKU-I] - 加载权息数据…… (StockManager.cpp:608)
2025-08-11 23:24:30.755 [HKU-I] - 加载板块信息…… (StockManager.cpp:181)
2025-08-11 23:24:31.845 [HKU-I] - 加载K线数据…… (StockManager.cpp:185)
2025-08-11 23:24:31.845 [HKU-I] - 预加载 day K线数据至缓存 (最大数量: 100000)! (StockManager.cpp:229)
2025-08-11 23:24:31.846 [HKU-I] - 2.26 秒数据加载完毕. (StockManager.cpp:191)
2025-08-11 23:24:31.847 [HKU-I] - 启动行情接收. (SpotAgent.cpp:39)
CPU times: total: 1.81 s
Wall time: 3.67 s

1 全局获取股票对象
==========

1.1 获取股票对象
-----------------

通过全局管理对象 sm，或使用函数 get_stock。股票标识格式“市场标识+股票代码”，市场标识：沪市sh，深市sz。

In [2]:
#s = getStock('sh000001')
s = sm['sh000001']
print(s)

Stock(SH, 000001, 上证指数, 指数, 1, 1990-12-20 00:00:00, +infinity)

1.2 遍历所有股票
-----------------

In [3]:
i = 0
#遍历所有股票
for s in sm:
    i += 1
    #print(s)
print("全部数量:", i)

len(sm)

全部数量: 8471

8471

2 通过板块（Block）遍历股票对象
================

通过 sm.get_stock("板块分类", "板块名称") 获取相应板块

In [4]:
blk = sm.get_block("指数板块", "沪深300")
print(len(blk))
# for s in blk:
#     if s.valid:
#         print(s)

300

3 查看权息信息
=======

In [5]:
ws = sm['sz000001'].get_weight()
for w in ws:
    print(w)

Weight(1990-03-01 00:00:00, 0, 1, 3.56, 0, 0, 0, 0, 0)
Weight(1991-04-03 00:00:00, 0, 0, 0, 0, 0, 4850.02, 2650, 0)
Weight(1991-05-02 00:00:00, 4, 0, 0, 3, 0, 8975.16, 3949.07, 0)
Weight(1991-08-17 00:00:00, 10, 0, 0, 0, 0, 8975.16, 3949.07, 0)
Weight(1992-03-23 00:00:00, 5, 0, 0, 2, 0, 8975.16, 3949.07, 0)
Weight(1993-05-24 00:00:00, 8.5, 1, 16, 3, 0, 26941.8, 18813, 0)
Weight(1993-06-30 00:00:00, 0, 0, 0, 0, 0, 26125.4, 18004.3, 0)
Weight(1994-07-09 00:00:00, 0, 0, 0, 0, 0, 28737.9, 19804.8, 0)
Weight(1994-07-11 00:00:00, 5, 1, 5, 5, 0, 28737.9, 19804.8, 0)
Weight(1994-07-14 00:00:00, 0, 0, 0, 0, 0, 43106.9, 29707.2, 0)
Weight(1995-09-25 00:00:00, 2, 0, 0, 3, 0, 43106.9, 29707.2, 0)
Weight(1995-09-27 00:00:00, 0, 0, 0, 0, 0, 51728.2, 35648.6, 0)
Weight(1996-05-27 00:00:00, 10, 0, 0, 0, 0, 51728.2, 35648.6, 0)
Weight(1996-05-29 00:00:00, 0, 0, 0, 0, 0, 103456, 71442.3, 0)
Weight(1997-08-25 00:00:00, 5, 0, 0, 2, 0, 103456, 71442.3, 0)
Weight(1997-08-27 00:00:00, 0, 0, 0, 0, 0, 155185, 107163, 0)
Weight(1999-10-18 00:00:00, 0, 0, 0, 6, 0, 155185, 107163, 0)
Weight(2000-11-06 00:00:00, 0, 3, 8, 0, 0, 155185, 107163, 0)
Weight(2000-12-08 00:00:00, 0, 0, 0, 0, 0, 194582, 139312, 0)
Weight(2001-10-15 00:00:00, 0, 0, 0, 0, 0, 194582, 140936, 0)
Weight(2002-07-23 00:00:00, 0, 0, 0, 1.5, 0, 194582, 140936, 0)
Weight(2003-09-29 00:00:00, 0, 0, 0, 1.5, 0, 194582, 140936, 0)
Weight(2007-06-18 00:00:00, 1, 0, 0, 0, 0, 194582, 140936, 0)
Weight(2007-06-20 00:00:00, 0, 0, 0, 0, 0, 208676, 155019, 0)
Weight(2007-12-28 00:00:00, 0, 0, 0, 0, 0, 229341, 170327, 0)
Weight(2007-12-31 00:00:00, 0, 0, 0, 0, 0, 229341, 170326, 0)
Weight(2008-01-21 00:00:00, 0, 0, 0, 0, 0, 229341, 175682, 0)
Weight(2008-06-26 00:00:00, 0, 0, 0, 0, 0, 229341, 204652, 0)
Weight(2008-06-27 00:00:00, 0, 0, 0, 0, 0, 238880, 214200, 0)
Weight(2008-10-31 00:00:00, 3, 0, 0, 0.335, 0, 310543, 278461, 0)
Weight(2009-06-22 00:00:00, 0, 0, 0, 0, 0, 310543, 292367, 0)
Weight(2009-06-30 00:00:00, 0, 0, 0, 0, 0, 310543, 292376, 0)
Weight(2009-10-15 00:00:00, 0, 0, 0, 0, 0, 310543, 292411, 0)
Weight(2010-06-28 00:00:00, 0, 0, 0, 0, 0, 310543, 310537, 0)
Weight(2010-06-29 00:00:00, 0, 0, 0, 0, 0, 348501, 310537, 0)
Weight(2010-06-30 00:00:00, 0, 0, 0, 0, 0, 348501, 310537, 0)
Weight(2010-12-31 00:00:00, 0, 0, 0, 0, 0, 348501, 310536, 0)
Weight(2011-06-30 00:00:00, 0, 0, 0, 0, 0, 348501, 310536, 0)
Weight(2011-08-05 00:00:00, 0, 0, 0, 0, 0, 512335, 310536, 0)
Weight(2012-10-19 00:00:00, 0, 0, 0, 1, 0, 512335, 310536, 0)
Weight(2013-06-20 00:00:00, 6, 0, 0, 1.7, 0, 819736, 496857, 0)
Weight(2013-11-12 00:00:00, 0, 0, 0, 0, 0, 819736, 557590, 0)
Weight(2014-01-09 00:00:00, 0, 0, 0, 0, 0, 952075, 557590, 0)
Weight(2014-06-12 00:00:00, 2, 0, 0, 1.6, 0, 1.14249e+06, 669106, 0)
Weight(2014-09-01 00:00:00, 0, 0, 0, 0, 0, 1.14249e+06, 983671, 0)
Weight(2015-04-13 00:00:00, 2, 0, 0, 1.74, 0, 1.37099e+06, 1.18041e+06, 0)
Weight(2015-05-21 00:00:00, 0, 0, 0, 0, 0, 1.43087e+06, 1.18041e+06, 0)
Weight(2016-05-23 00:00:00, 0, 0, 0, 0, 0, 1.43087e+06, 1.21926e+06, 0)
Weight(2016-06-16 00:00:00, 2, 0, 0, 1.53, 0, 1.71704e+06, 1.46312e+06, 0)
Weight(2017-01-09 00:00:00, 0, 0, 0, 0, 0, 1.71704e+06, 1.6918e+06, 0)
Weight(2017-07-21 00:00:00, 0, 0, 0, 1.58, 0, 1.71704e+06, 1.6918e+06, 0)
Weight(2017-12-31 00:00:00, 0, 0, 0, 0, 0, 1.71704e+06, 1.6918e+06, 0)
Weight(2018-05-21 00:00:00, 0, 0, 0, 0, 0, 1.71704e+06, 1.71702e+06, 0)
Weight(2018-07-12 00:00:00, 0, 0, 0, 1.36, 0, 1.71704e+06, 1.71702e+06, 0)
Weight(2019-06-26 00:00:00, 0, 0, 0, 1.45, 0, 1.71704e+06, 1.71702e+06, 0)
Weight(2019-06-30 00:00:00, 0, 0, 0, 0, 0, 1.71704e+06, 1.71702e+06, 0)
Weight(2019-09-18 00:00:00, 0, 0, 0, 0, 0, 1.94059e+06, 1.94058e+06, 0)
Weight(2020-05-28 00:00:00, 0, 0, 0, 2.18, 0, 1.94059e+06, 1.94058e+06, 0)
Weight(2020-12-31 00:00:00, 0, 0, 0, 0, 0, 1.94059e+06, 1.94058e+06, 0)
Weight(2021-05-14 00:00:00, 0, 0, 0, 1.8, 0, 1.94059e+06, 1.94058e+06, 0)
Weight(2021-12-31 00:00:00, 0, 0, 0, 0, 0, 1.94059e+06, 1.94055e+06, 0)
Weight(2022-06-30 00:00:00, 0, 0, 0, 0, 0, 1.94059e+06, 1.94055e+06, 0)
Weight(2022-07-22 00:00:00, 0, 0, 0, 2.28, 0, 1.94059e+06, 1.94055e+06, 0)
Weight(2023-06-14 00:00:00, 0, 0, 0, 2.85, 0, 1.94059e+06, 1.94055e+06, 0)
Weight(2024-06-14 00:00:00, 0, 0, 0, 7.19, 0, 1.94059e+06, 1.94055e+06, 0)
Weight(2024-06-30 00:00:00, 0, 0, 0, 0, 0, 1.94059e+06, 1.94056e+06, 0)
Weight(2024-10-10 00:00:00, 0, 0, 0, 2.46, 0, 1.94059e+06, 1.94056e+06, 0)
Weight(2024-12-31 00:00:00, 0, 0, 0, 0, 0, 1.94059e+06, 1.94056e+06, 0)
Weight(2025-06-12 00:00:00, 0, 0, 0, 3.62, 0, 1.94059e+06, 1.94056e+06, 0)

In [6]:
ws.to_df()

,datetime,countAsGift,countForSell,priceForSell,bonus,countOfIncreasement,totalCount,freeCount,suogu
0,1990-03-01,0.0,1.0,3.56,0.00,0.0,0.000000e+00,0.000000e+00,0.0
1,1991-04-03,0.0,0.0,0.00,0.00,0.0,4.850017e+03,2.650000e+03,0.0
2,1991-05-02,4.0,0.0,0.00,3.00,0.0,8.975164e+03,3.949072e+03,0.0
3,1991-08-17,10.0,0.0,0.00,0.00,0.0,8.975164e+03,3.949072e+03,0.0
4,1992-03-23,5.0,0.0,0.00,2.00,0.0,8.975164e+03,3.949072e+03,0.0
...,...,...,...,...,...,...,...,...,...
64,2024-06-14,0.0,0.0,0.00,7.19,0.0,1.940592e+06,1.940555e+06,0.0
65,2024-06-30,0.0,0.0,0.00,0.00,0.0,1.940592e+06,1.940562e+06,0.0
66,2024-10-10,0.0,0.0,0.00,2.46,0.0,1.940592e+06,1.940562e+06,0.0
67,2024-12-31,0.0,0.0,0.00,0.00,0.0,1.940592e+06,1.940557e+06,0.0
68,2025-06-12,0.0,0.0,0.00,3.62,0.0,1.940592e+06,1.940557e+06,0.0